[package]
name = "pg_dbms_job"
version = "1.5.0-rust"
edition = "2021"

[dependencies]
chrono = "0.4"
postgres = "0.19"
signal-hook = "0.3"
nix = { version = "0.27", default-features = false, features = ["signal", "process", "fs"] }
fallible-iterator = "0.2"
